name: CD

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - ".github/**"
      - "**/README*"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  # create-release:
  #   needs: [ci]
  #   runs-on: ubuntu-latest
  #   if: startswith(github.ref, 'refs/tags/v')
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

  publish-npm:
    needs: [ci]
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile --non-interactive
      - run: yarn run build

      - name: Publish to npm
        run: bash scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
